ebuy/urls.py
from django.conf.urls import url,include
from django.contrib import admin

import main.urls
from main.views import HomeView, CategoryView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(main.urls)),



]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from main.views import *

app_name = 'main'
urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'about-us/', AboutView.as_view(), name='about'),
    url(r'contact-us/', ContactUsView.as_view(), name='contact'),
    url(r'registration/', RegistrationView.as_view(), name='registration'),
    url(r'login/', LoginView.as_view(), name='login'),
    #url(r'search/', include('haystack.urls'), name='search'),
    #url(r'test/', listing, name=''),
    url(r'logout/', LogoutView.as_view(), name='logout'),
    url(r'cart/', CartView.as_view(), name='cart'),
    url(r'business/', BusinessView.as_view(), name='business'),
    url(r'^categories/(?P<cat_name>[\w|\W]+)/', CategoryView.as_view(), name='categories'),
    url(r'^products/(?P<cat_name>[\w|\W]+)/(?P<product_name>[\w|\W]+)', ProductView.as_view(), name='products'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

import threading
from main import currency

#threading.Timer(86400,currency.currency_converter()).start()

main/models.py
from django.db import models
from django.contrib.auth.models import User, Permission
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import RegexValidator

class Package(models.Model):
    name = models.CharField(null=False, max_length=50)
    description = models.CharField(null=False, max_length=1000)
    short_description = models.CharField(null=False, max_length=70)
    price = models.FloatField(null=True)
    discounted_price = models.FloatField(null=False, default=0)
    discount_rate = models.PositiveIntegerField(null=False, default=0)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True)
    main_photo = models.FileField(null=False)
    amount = models.PositiveIntegerField(null=False, default=0)
    amount_sold = models.PositiveIntegerField(null=False, default=0)
    kwd_price = models.FloatField(null=False, default=0)
    omr_price = models.FloatField(null=False, default=0)
    bhd_price = models.FloatField(null=False, default=0)
    jod_price = models.FloatField(null=False, default=0)
    lbp_price = models.FloatField(null=False, default=0)
    qar_price = models.FloatField(null=False, default=0)
    sar_price = models.FloatField(null=False,default=0)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.discount_rate > 0:
            self.discounted_price = self.price - (self.price * self.discount_rate)
            super().save(*args, **kwargs)
        else:
            super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(null=False, max_length=50)
    photo = models.FileField(null=False)

    def __str__(self):
        return self.name

#    from = models.CharField(null=False, max_lenght=3)
#    to = models.CharField(null=False, max_lenght=3)
#    rate = models.(null=False)


class PackageProduct(models.Model):
    name = models.CharField(null=False, max_length=50)
    description = models.CharField(null=False, max_length=1000)
    package = models.ForeignKey('Package', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.name


class HotNews(models.Model):
    news = models.CharField(null= False, max_length=150)

    def __str__(self):
        return self.news[:25]


class Product(models.Model):
    name = models.CharField(null=False, max_length=50)
    description = models.CharField(null=False, max_length=2000)
    short_description = models.CharField(null=False, max_length=70)
    price = models.FloatField(null=True)
    discount_rate = models.PositiveIntegerField(null=False, default=0)
    discounted_price = models.FloatField(null=False, default=0)
    amount = models.IntegerField(null=False, default=1)
    amount_sold = models.IntegerField(null=False, default=0)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=False)
    photo = models.FileField(null=False)
    kwd_price = models.FloatField(null=False, default=0)
    omr_price = models.FloatField(null=False, default=0)
    bhd_price = models.FloatField(null=False, default=0)
    jod_price = models.FloatField(null=False, default=0)
    lbp_price = models.FloatField(null=False, default=0)
    qar_price = models.FloatField(null=False, default=0)
    sar_price = models.FloatField(null=False,default=0)

    def __str__(self):
        return self.name

    def get_product_category(self):
        return self.category

    def save(self, *args, **kwargs):
        if self.discount_rate > 0:
            print(self.discount_rate)
            print(self.price)
            self.discounted_price = self.price - (self.price * (self.discount_rate/100))
            print(self.discounted_price)
            super().save(*args, **kwargs)
        else:
            super().save(*args, **kwargs)



class Comment(models.Model):
    comment = models.TextField(null=False, max_length=255, help_text="Your comment here")
    product = models.ForeignKey('Product', on_delete=models.CASCADE)


class ProductPhoto(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, null=False, related_name='images')
    photo = models.FileField(null=False)

    def __str__(self):
        return self.product.name


class PackagePhoto(models.Model):
    package = models.ForeignKey('Package', on_delete=models.CASCADE, null=False)
    photo = models.FileField(null=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    phone_number = models.CharField(max_length=17, blank=False)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    def __str__(self):
        return "%s's profile" % self.user


class Cart(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, null=True)
    package = models.ForeignKey('Package',on_delete=models.CASCADE, null=True)
    price = models.FloatField(null=False)
    quantity = models.PositiveIntegerField(null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Currency(models.Model):
    rate = models.FloatField(null=False)
    from_currency = models.CharField(null=False, max_length=3)
    to_currency = models.CharField(null=False, max_length=3)

main/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.views.generic import View
from main.models import *
import re
import requests
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger




class HomeView(View):
    template_name = 'main/index.html'

    def get(self, request):
        cats = Category.objects.all()
        context = {'categories': get_categories(), 'news': get_news(), 'cats': cats, 'offers':get_offers()}
        return render(request, 'main/index.html', context)

    def post(self, request):
        if 'searchkey' in request.POST:
            print("I am in ")
            text = request.POST.get('searchkey', '')
            if text:
                product = Product.objects.all().filter(name__contains=text).exists()
                if product:
                    pro = Product.objects.get(name__contains=text)
                    cat = pro.category
                    catname = cat.name
                    print(cat)
                    return redirect('main:products', cat_name=catname.replace(' ', '-'), product_name=pro.name)


class BusinessView(View):
    template_name = 'main/business.html'

    def get(self, request):
        categories_names = get_categories()
        context = {'categories': categories_names, 'news': get_news()}
        return render(request, 'main/business.html', context)


def get_categories():
    cat_names = []
    categories = Category.objects.all()
    for category in categories:
        cat_names.append(category.name)
    categories_names = []
    for name in cat_names:
        categories_names.append(re.sub('\s+', '-', name))
    return categories_names


def get_news():
    news = []
    hot_news = HotNews.objects.all()
    if hot_news:
        for n in hot_news:
            news.append(n.news)
    return news


def get_currency(value, code):
    if code == "KWD":
        r = requests.get('http://free.currencyconverterapi.com/api/v5/convert?q=' + 'AED_' + code + '&compact=ultra')
        json = r.json()
        rate = json['AED_' + code]
        converted = float(rate) * float(value)
        return float("{0:.2f}".format(converted))
    elif code == 'OMR':
        r = requests.get('http://free.currencyconverterapi.com/api/v5/convert?q=' + 'AED_' + code + '&compact=ultra')
        json = r.json()
        rate = json['AED_' + code]
        converted = float(rate) * float(value)
        return float("{0:.2f}".format(converted))
    elif code == 'BHD':
        r = requests.get('http://free.currencyconverterapi.com/api/v5/convert?q=' + 'AED_' + code + '&compact=ultra')
        json = r.json()
        rate = json['AED_' + code]
        converted = float(rate) * float(value)
        return float("{0:.2f}".format(converted))
    elif code == 'AED':
        tax = float(value) * (5 / 100)
        final = float(value + tax)
        return float("{0:.2f}".format(final))
    elif code == 'JOD':
        r = requests.get('http://free.currencyconverterapi.com/api/v5/convert?q=' + 'AED_' + code + '&compact=ultra')
        json = r.json()
        rate = json['AED_' + code]
        converted = float(rate) * float(value)
        price_with_tax = float(converted + (converted * (16 / 100)))
        return float("{0:.2f}".format(price_with_tax))
    elif code == 'SAR':
        r = requests.get('http://free.currencyconverterapi.com/api/v5/convert?q=' + 'AED_' + code + '&compact=ultra')
        json = r.json()
        rate = json['AED_' + code]
        converted = float(rate) * float(value)
        price_with_tax = float(converted + (converted * (5 / 100)))
        return float("{0:.2f}".format(price_with_tax))
    elif code == 'QAR':
        r = requests.get('http://free.currencyconverterapi.com/api/v5/convert?q=' + 'AED_' + code + '&compact=ultra')
        json = r.json()
        result = json['AED_' + code]
        final = float(result * value)
        return float("{0:.2f}".format(final))
    elif code == 'LBP':
        r = requests.get('http://free.currencyconverterapi.com/api/v5/convert?q=' + 'AED_' + code + '&compact=ultra')
        json = r.json()
        rate = json['AED_' + code]
        converted = float(rate) * float(value)
        price_with_tax = float(converted + (converted * (11 / 100)))
        return float("{0:.2f}".format(price_with_tax))


def get_offers():
    return Product.objects.filter(discount_rate__gt=0)


class ProductView(View):
    template_name = 'main/product.html'

    def get(self, request, cat_name, product_name):
        productName = product_name.replace('-', ' ')
        isProduct = True

        if Product.objects.all().filter(name=productName).exists():
            try:
                product = Product.objects.get(name=productName)
                product_photos = ProductPhoto.objects.all()
            except (Product.DoesNotExist, ProductPhoto.DoesNotExist):
                product_photos = None
                product = None
            context = {'item': product, 'category': cat_name, 'categories': get_categories(), 'isProduct': isProduct,
                       'product_photos': product_photos, 'news': get_news(), 'offers': get_offers()}

        else:
            isProduct = False
            try:
                package = Package.objects.get(name=productName)
                package_photos = PackagePhoto.objects.all()
                package_products = PackageProduct.objects.all().filter(package=package)
            except (Package.DoesNotExist, PackagePhoto.DoesNotExist):
                package_photos = None
                package = None
                package_products = None

            context = {'item': package, 'category': cat_name, 'categories': get_categories(), 'isProduct': isProduct,
                       'packagephotos': package_photos, 'packageproducts': package_products, 'news': get_news(),
                       'offers': get_offers()}

        return render(request, 'main/product.html', context)

    def post(self, request, cat_name, product_name):
        quantity = request.POST.get('quantity', 1)
        currency = self.request.POST.get('currency', 'usd')
        name = request.POST.get('itemName')
        id = request.POST.get('itemId')
        item_type = request.POST.get('type')
        price = request.POST.get('price')
        item_to_add = {

            "id": id,
            "quantity": quantity,
            "price": price,
            "currency": currency,
            "type": item_type,

        }
        if 'cart_names' not in request.session:
            request.session['cart_names'] = []
        if 'cart' not in request.session:
            request.session['cart'] = {'items': {}}
        dict = request.session.get("cart", {})
        dict['items'][name] = item_to_add
        request.session['cart'] = dict
        return HttpResponseRedirect(self.request.path_info)


class CategoryView(View):
    template_name = 'main/category.html'

    def get(self, request, cat_name):
        category_name = cat_name.replace('-', ' ')
        category = Category()
        try:
            category = Category.objects.get(name=category_name)
        except Category.DoesNotExist:
            category = None
        try:
            products = Product.objects.all().filter(category=category)
            product_photos = ProductPhoto.objects.all()
        except Product.DoesNotExist:
            products = None
            product_photos = None
        try:
            packages = Package.objects.all().filter(category=category)
            package_photos = PackagePhoto.objects.all()
        except Package.DoesNotExist:
            packages = None
            package_photos = None
        context = {'categoryurl': cat_name, 'products': products, 'packages': packages, 'categoryName': category_name,
                   'categories': get_categories(), 'productphotos': product_photos, 'packagephotos': package_photos,
                   'active': 'active', 'news': get_news(), 'offers':get_offers()}

        return render(request, 'main/category.html', context)


class AboutView(View):
    template_name = 'main/about.html'

    def get(self, request):

        context = {'categories': get_categories(), 'news': get_news()}
        return render(request, 'main/about.html', context)


def listing(request):
    contact_list = Product.objects.all()
    paginator = Paginator(list(contact_list), 1)

    page = request.GET.get('page')
    contacts = paginator.page(page)
    return render(request, 'main/list.html', {'contacts': contacts})


class ContactUsView(View):
    template_name = 'main/contact.html'

    def get(self, request):
        context = {'categories': get_categories(), 'news': get_news()}
        return render(request, 'main/contact.html', context)

    def post(self, request):
        email = self.request.POST.get('email')
        if not re.match("[^@]+@[^@]+\.[^@]+", email):
            context = {'categories': get_categories(), 'msg': 'Invalid email address'}
            return render(request, 'main/contact.html', context)
        phone = self.request.POST.get('phone')
        message = self.request.POST.get('message')
        name = self.request.POST.get('name')
        # if name and message and phone!= "":
        send_mail("Business User",
                  "Name: " + name + "\n" + "User Email: " + email + "\n" + "User Phone: " + phone + "\n" + "Message: " + message,
                  settings.EMAIL_HOST_USER, ['20140165@fa-hists.edu.eg'], fail_silently=False)
        messages.success(request, 'Thank you for sending us an email!')
        return render(request, 'main/contact.html')


class RegistrationView(View):
    template_name = 'main/registration.html'

    def get(self, request):

main/templates/main/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action='https://www.2checkout.com/checkout/purchase' method='post'>
<input type='hidden' name='sid' value='203646668' />
<input type='hidden' name='mode' value='2CO' />
<input type='hidden' name='li_0_type' value='product' />
<input type='hidden' name='li_0_name' value='invoice123' />
<input type='hidden' name='li_0_price' value='50' />
<input type='hidden' name='li_0_tangible' value='Y' />
<input type='hidden' name='li_1_type' value='shipping' />
<input type='hidden' name='li_1_name' value='Express Shipping' />
<input type='hidden' name='li_1_price' value='13.99' />
<input type='hidden' name='card_holder_name' value='Checkout Shopper' />
<input type='hidden' name='street_address' value='123 Test Address' />
<input type='hidden' name='street_address2' value='Suite 200' />
<input type='hidden' name='city' value='Columbus' />
<input type='hidden' name='state' value='OH' />
<input type='hidden' name='zip' value='43228' />
<input type='hidden' name='country' value='USA' />
<input type='hidden' name='ship_name' value='Checkout Shopper' />
<input type='hidden' name='ship_street_address' value='123 Test Address' />
<input type='hidden' name='ship_street_address2' value='Suite 200' />
<input type='hidden' name='ship_city' value='Columbus' />
<input type='hidden' name='ship_state' value='OH' />
<input type='hidden' name='ship_zip' value='43228' />
<input type='hidden' name='ship_country' value='USA' />
<input type='hidden' name='email' value='moamen_mohammed@hotmail.com' />
<input type='hidden' name='phone' value='614-921-2450' />
<input name='submit' type='submit' value='Checkout' />
</form>
</body>

</html>
<script src="https://www.2checkout.com/static/checkout/javascript/direct.min.js"></script>

main/templates/main/contact.html
{% load static %}
{% load url_mods %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta shopping-cart -->
      <title>فور ايفر - تواصل معنا</title>
   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title -->
   <title>  </title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css' %}" />
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cairo">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}" />
    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'main/css/stylesheet.css' %}" />
    <link rel="shortcut icon" href="{%  static 'main/images/logo.png' %}">
</head>

<body>

    <!-- Login Form -->
    <div id='fixedLogin' class='login'>
        <div class='container'>
            <div id='loginWindow' class='window'>
                <i id='close' class='fa fa-close'></i>
                <h3>تسجيل الدخول</h3>
                <hr>
                <form action="{% url 'main:login' %}" method="POST">
                    <div class='form-group'>
                        <input type="text" name="username" placeholder='أسم المستخدم' class='form-control' />
                        <i class='fa fa-user'></i>
                    </div>
                    <div class='form-group'>
                        <input type="password" name="password" placeholder='كلمة المرور' class='form-control' />
                        <i class='fa fa-lock'></i>
                    </div>
                    <div class='row'>
                        <div class='col-sm-6'>
                            <input type='submit' value='دخول' class='form-control' />
                        </div>
                        <div class='col-sm-6'>
                            <a href='{% url 'main:registration' %}'>إنشاء حساب ؟</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Login Form -->

    <!-- Contact us fixed btn -->
   <div class='contact-fixed-btn'>
        <a href='{% url 'main:contact' %}'>
            <p>
                <i class='fa fa-phone'></i>
            </p>
        <span>Contact Us</span>
        </a>
    </div>
    <!-- Contact us fixed btn -->
    <!-- Contact us fixed btn -->

    <!-- MOB: Hot & News In Uppernav -->
    <div class='uppernav'>
        <div class='container'>
            <div class='faded-upper-text'>
                 {% for news in news %}
               {% if forloop.counter == 1 %}
               <div class='box active'>
                  <p>{{ news }}</p>
               </div>
               {% else %}
               <div class='box hidden'>
                  <p>{{ news }}</p>
               </div>
               {% endif %}
               {% endfor %}
            </div>
        </div>
    </div>
    <!-- MOB: Hot & News In Uppernav -->

    <!-- Nav -->
    <div class='nav'>
        <div class='container'>
            <div class='logo'>
                <a href='{% url 'main:home' %}'><img src='{% static 'main/images/logo.png' %}' class='img-fluid' /></a>
            </div>
            <div class='faded-text'>
                {% for news in news %}
               {% if forloop.counter == 1 %}
               <div class='box active'>
                  <p>{{ news }}</p>
               </div>
               {% else %}
               <div class='box hidden'>
                  <p>{{ news }}</p>
               </div>
               {% endif %}
               {% endfor %}
            </div>
           <div class='rhs'>
               {% if user.is_authenticated %}
               {% else %}
               <i class='fa fa-user login-form-icon'></i>
               {% endif %}
               {% if user.is_authenticated %}
               <div class='logged-in'>
                  <ul class='list-unstyled'>
                     <li>&nbsp;<i class='fa fa-sort-down'></i>{{ user.username }}</li>
                     <li><a href='{% url 'main:logout' %}'>Logout&nbsp;<i class='fa fa-close'></i></a></li>
                  </ul>
               </div>
               {% endif %}
               <!--<i class='fa fa-search search-icon'></i>-->
               <a href='{% url 'main:cart' %}' target="_blank">
                  <p>
                     <i class='fa fa-shopping-cart cart-icon'></i>
                     <span class='cart-num'>0</span>
                  </p>
               </a>
            </div>
        </div>
    </div>
    <!-- Nav -->
    <!-- Search Bar -->
    <div class='search'>
        <div class='container'>
            <form action="" method="">
                <input type="search" name='searchkey' class='form-control' placeholder='بحث' />
                <i class='fa fa-close search-close'></i>
                <input type='submit' value='بحث' class='btn btn-success'/>
            </form>
        </div>
    </div>
    <!-- Search Bar -->
    <!-- Categories Navigation -->
    <div class='cats-nav'>
        <div class='container'>
            <ul class='cats-navigation list-unstyled'>
                 <li class='active'><a href='{% url 'main:home' %}'>الرئيسيه</a></li>
               {% for category in categories %}
               {% load url_mods %}
               <li><a href='{% url 'main:categories' cat_name=category %}'>{{ category|dashtospace}}</a></li>
               {% endfor %}
               <li><a href='{% url 'main:about' %}'>من نحن</a></li>
               <li><a href='{% url 'main:business' %}'>Business</a></li>
            </ul>
        </div>
    </div>
    <!-- Categories Navigation -->

    <!-- Start Mobile Nav -->

    <div class='mobnav'>
        <div class='container'>
            <div class='nav-content'>
                <div class='icon pull-left'>
                    <div class='hamburger'></div>
                </div>
                <ul class='list-unstyled mlinks'>
                     <li class='active'><a href='{% url 'main:home' %}'>الرئيسيه</a></li>
               {% for category in categories %}
               {% load url_mods %}
               <li><a href='{% url 'main:categories' cat_name=category %}'>{{ category|dashtospace}}</a></li>
               {% endfor %}
               <li><a href='{% url 'main:about' %}'>من نحن</a></li>
               <li><a href='{% url 'main:business' %}'>Business</a></li>
                </ul>
            </div>
        </div>
    </div>

    <!-- End Mobile Nav -->

    <!-- Contact Form -->
    <div class='global-icon'><i class='fa fa-phone fa-2x'></i></div>
    <div class='contact-form'>
        <div class='container'>
            <h3>أتصل بنا
                <div class='new-line'><span style="width: 100px"></span></div>
            </h3>
            <form action="" method="">
                <div class='form-group'>
                    <input type='text' name="name" placeholder='أسم المستخدم' class='form-control' />
                    <i class='fa fa-user'></i>
                </div>
                <div class='form-group'>
                    <input type='email' name="email" placeholder='البريد الألكتروني' class='form-control' />
                    <i class='fa fa-envelope'></i>
                </div>
                <div class='form-group'>
                    <input type='text' name="phone" placeholder='رقم الهاتف' class='form-control' />
                    <i class='fa fa-phone'></i>
                </div>
                <div class='form-group'>
                    <textarea class='form-control textarea' placeholder="أكتب رسالتك"></textarea>
                    <i class='fa fa-edit'></i>
                </div>
                {% csrf_token %}
                <input type="submit" value="إرسال" class='form-control btn btn-primary' />
            </form>
        </div>
    </div>
    <!-- Contact Form -->

    <!-- Footer -->
    <div class='footer'>
        <div class='container'>
            <div class='row'>
                <div class='col'>
                    <div class='footer-brand'>
                        <p>هنا يكتب نص يشرح محتوي الموقع و ما هي اهدافها </p>
                        <ul class='footer-media list-unstyled'>
                            <li><a href='https://www.facebook.com/malak.fathy.161' target="_blank"><i class='fa fa-facebook'></i></a></li>
                            <li class='whatisapp'><a href='#'><i class='fa fa-whatsapp'></i></a></li>
                            <li class='gemail'><a href='#'><i class='fa fa-google'></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class='col'>
                    <ul class='sitemap list-unstyled row'>
                        <div class='col-6'>
                            <li>خريطه الموقع</li>
                            <li class="active">
                               <a href="{% url 'main:home' %}">الرئيسيه <span class="sr-only">(current)</span></a>
                            </li>
                            {% for category in categories %}
                        <li>
                           <a href="{% url 'main:categories' cat_name=category|spacetodash %}">{{ category|dashtospace }}</a>
                        </li>
                        {% endfor %}

                        </div>
                        <div class='col-6'>
                            <li>
                               <a href="{% url 'main:business' %}">Business</a>
                            </li>
                            <li>
                                <a href="{% url 'main:about' %}">من نحن</a>
                            </li>
                            <li>
                                  <a href="{% url 'main:contact' %}">أتصل بنا</a>
                            </li>
                        </div>
                    </ul>
                </div>
                <div class='col'>
                    <a href='{% url 'main:home' %}' target="_blank"><img src='{% static 'main/images/logo.png' %}' alt='' /></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer -->

    <!-- Sub Footer -->
    <div class='sub-footer'>
        <p>Copyright © 2018. foreverhealthyandbeauty.com All Rights Reserved.</p>
    </div>
    <!-- Sub Footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'main/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'main/js/popper.min.js' %}"></script>
    <!-- Javascript Tooltip library -->
    <script src="{% static 'main/js/bootstrap.min.js' %}"></script>
	<script type="text/javascript">
    (function () {
        var options = {
            whatsapp: "+966536359930", // WhatsApp number
            company_logo_url: "//static.whatshelp.io/img/flag.png", // URL of company logo (png, jpg, gif)
            greeting_message: "Hello, how may we help you? Just send us a message now to get assistance.", // Text of greeting message
            call_to_action: "Message us", // Call to action
            position: "right", // Position may be 'right' or 'left'
        };
        var proto = document.location.protocol, host = "whatshelp.io", url = proto + "//static." + host;
        var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
        s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
        var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
    })();
</script>
    <script src='{% static 'main/js/plugins.js' %}'></script>
</body>

</html>

main/templates/main/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for contact in contacts %}
    {# Each "contact" is a Contact model object. #}
    {{ contact.name|upper }}<br />
    ...
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ contacts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ contacts.name }} of {{ contacts.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">next</a>
            <a href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</body>
</html>